package net.cacko.watts.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme
val PrimaryLight = Color(0xFF8B5000)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDCBE)
val OnPrimaryContainerLight = Color(0xFF2D1600)
val SecondaryLight = Color(0xFF725A41)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFEDED2)
val OnSecondaryContainerLight = Color(0xFF291805)
val TertiaryLight = Color(0xFF58633A)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDCE8B4)
val OnTertiaryContainerLight = Color(0xFF161E01)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFFFBFF)
val OnBackgroundLight = Color(0xFF201B16)
val SurfaceLight = Color(0xFFFFFBFF)
val OnSurfaceLight = Color(0xFF201B16)
val SurfaceVariantLight = Color(0xFFF0E0D0)
val OnSurfaceVariantLight = Color(0xFF4F4539)
val OutlineLight = Color(0xFF817567)

// Dark Scheme
val PrimaryDark = Color(0xFFFFB870)
val OnPrimaryDark = Color(0xFF4A2800)
val PrimaryContainerDark = Color(0xFF693C00)
val OnPrimaryContainerDark = Color(0xFFFFDCBE)
val SecondaryDark = Color(0xFFE0C1A3)
val OnSecondaryDark = Color(0xFF402D17)
val SecondaryContainerDark = Color(0xFF58432B)
val OnSecondaryContainerDark = Color(0xFFFEDED2)
val TertiaryDark = Color(0xFFC0CC9B)
val OnTertiaryDark = Color(0xFF2B3410)
val TertiaryContainerDark = Color(0xFF414B24)
val OnTertiaryContainerDark = Color(0xFFDCE8B4)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF201B16)
val OnBackgroundDark = Color(0xFFEDE0D4)
val SurfaceDark = Color(0xFF201B16)
val OnSurfaceDark = Color(0xFFEDE0D4)
val SurfaceVariantDark = Color(0xFF4F4539)
val OnSurfaceVariantDark = Color(0xFFD3C4B4)
val OutlineDark = Color(0xFF9C8F80)

// Energy Specific Colors (for dynamic usage)
val EnergyBlue = Color(0xFF00B0FF)
val EnergyGreen = Color(0xFF4CAF50)
val EnergyAmber = Color(0xFFFFC107)
val EnergyOrange = Color(0xFFFF9800)
val EnergyRed = Color(0xFFFF5252)
